name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2

      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn package
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
