name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install

      # bumps the repo version to a pre-release version based on the current commit
      - name: Bump Prerelease
        run: tools/bump-prerelease.sh

      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Package
        run: yarn package
      # - name: Publish
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > ~/.npmrc
      #     npm publish

          