name: Build
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/setup-java@v1
        with:
          java-version: 9.x
      - name: Setup
        run: npm install -g yarn
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Package
        run: yarn package
      # - name: Publish
      #   run: |
      #     echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}" > ~/.npmrc
      #     npm publish

          