name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install

      # bumps the repo version to a pre-release version based on the current commit
      - name: Bump Prerelease
        run: yarn prerelease

      # compile, test and package
      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Package
        run: yarn package
      
      # publish preprelease
      - name: Publish
        run: yarn run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
