name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install

      # bumps the repo version to a pre-release version based on the current commit
      - name: Bump Prerelease
        run: yarn prerelease

      # compile, test and package
      - name: Build and Test
        run: |
          yarn build
          yarn test

      - name: Package
        run: yarn package
      
      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
