name: Release
on:
  push:
    branches:
      - master
    
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn bump ./package.json
      - run: yarn build
      - run: yarn test
      - run: yarn package

      # publish to package managers only if this is a new version
      
      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_REGISTRY: npm.pkg.github.com
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
